({_obj:"object",
    animationProtection:{
        _obj:"animationProtection", 
        animationPropagate:true, 
        animationUnifyEffects:false, 
        animationUnifyPosition:false, 
        animationUnifyVisibility:false}, 
    artboardEnabled:false, 
    background:false,
    bounds:{
        _obj:"rectangle", 
        bottom:{_unit:"pixelsUnit", _value:453}, 
        height:{_unit:"pixelsUnit", _value:266}, 
        left:{_unit:"pixelsUnit", _value:171}, 
        right:{_unit:"pixelsUnit", _value:468}, 
        top:{_unit:"pixelsUnit", _value:187}, 
        width:{_unit:"pixelsUnit", _value:297}}, 
    boundsNoEffects:{_obj:"rectangle", 
        bottom:{_unit:"pixelsUnit", _value:453}, 
        height:{_unit:"pixelsUnit", _value:266}, 
        left:{_unit:"pixelsUnit", _value:171}, 
        right:{_unit:"pixelsUnit", _value:468}, 
        top:{_unit:"pixelsUnit", _value:187}, 
        width:{_unit:"pixelsUnit", _value:297}}, 
    boundsNoMask:{_obj:"rectangle", 
        bottom:{_unit:"pixelsUnit", _value:453}, 
        height:{_unit:"pixelsUnit", _value:266}, 
        left:{_unit:"pixelsUnit", _value:171}, 
        right:{_unit:"pixelsUnit", _value:468}, 
        top:{_unit:"pixelsUnit", _value:187}, 
        width:{_unit:"pixelsUnit", _value:297}}, 
    channelRestrictions:[
        ({_enum:"channel", _value:"red"}), 
        ({_enum:"channel", _value:"grain"}), 
        ({_enum:"channel", _value:"blue"})], 
    color:{_enum:"color", _value:"none"}, 
    count:2, 
    fillEnabled:false, 
    fillOpacity:255, 
    filterMaskDensity:255, 
    filterMaskFeather:0, 
    generatorSettings:{_obj:"generatorSettings"}, 
    globalAngle:90, 
    group:false, 
    hasFilterMask:false, 
    hasUserMask:false, 
    hasVectorMask:false, 
    itemIndex:2, 
    keyOriginType:[], 
    layerFXVisible:false, 
    layerID:2, 
    layerKind:5, 
    layerLocking:{
        _obj:"layerLocking", 
        protectAll:false, 
        protectArtboardAutonest:false, 
        protectComposite:false, 
        protectPosition:false, 
        protectTransparency:false}, 
    layerSection:{_enum:"layerSectionType", _value:"layerSectionContent"}, 
    mode:{_enum:"blendMode", _value:"normal"}, 
    name:"Vector Smart Object", 
    opacity:255, 
    parentLayerID:-1, 
    preserveTransparency:false, 
    proportionalScaling:false, 
    smartObject:{_obj:"smartObject", 
    documentID:"uuid:eda5a5a6-5652-5449-932e-c0876c239e1b", 
    fileReference:"Vector Smart Object.ai", 
    linked:false, 
    placed:{_enum:"placed", _value:"vectorData"}}, 
    smartObjectMore:{ID:"11821d0e-4e14-3c42-ab77-2d6ed4bc65ed", 
    antiAliasType:16, 
    comp:-1, 
    crop:7, 
    duration:{denominator:600, numerator:0}, 
    frameCount:1, 
    frameStep:{denominator:600, numerator:0}, 
    nonAffineTransform:[171, 187, 468, 187, 468, 453, 171, 453], 
    pageNumber:1, 
    placed:"a84ecd89-885a-2743-83a1-718e8d621e5b", 
    resolution:{_unit:"densityUnit", _value:72}, 
    size:{_obj:"paint", height:265.971008300781, width:296.699005126953}, 
    totalPages:1, 
    transform:[171, 187, 468, 187, 468, 453, 171, 453], 
    type:1, 
    warp:{_obj:"warp", bounds:{_obj:"classFloatRect", bottom:0, left:0, right:0, top:0}, 
    uOrder:4, 
    vOrder:4, 
    warpPerspective:0, 
    warpPerspectiveOther:0, 
    warpRotate:{_enum:"orientation", _value:"horizontal"}, 
    warpStyle:{_enum:"warpStyle", _value:"warpNone"}, 
    warpValue:0}}, 
    targetChannels:[({_index:1, _ref:"channel"}),({_index:2, _ref:"channel"}), ({_index:3, _ref:"channel"})], 
    textWarningLevel:0, 
    useAlignedRendering:false, 
    userMaskDensity:255, 
    userMaskFeather:0, 
    vectorMaskDensity:255, 
    vectorMaskEmpty:true, 
    vectorMaskFeather:0, 
    visible:true, 
    visibleChannels:[({_index:1, _ref:"channel"}), ({_index:2, _ref:"channel"}), ({_index:3, _ref:"channel"})]})